/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLayeredPane;

/**
 *
 * @author Ken Jaya
 */
public class Template extends javax.swing.JFrame {

    /**
     * Creates new form Template
     */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 818, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 529, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    
    public Template() throws IOException {
        // Initialize components (including jLayeredPane1)
        initComponents();

        // Set JFrame properties
        setTitle("Template with Background");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(982, 989);

        // Add the background panel to the layered pane
        Background background = new Background("assets/background.png");
        background.setLayout(new java.awt.GridBagLayout()); // Use GridBagLayout for centering
        background.setBounds(0, 0, getWidth(), getHeight());
        jLayeredPane1.add(background, JLayeredPane.DEFAULT_LAYER);

        // Add the Login panel to the background and center it
        Login lg = new Login();
        lg.setPreferredSize(new java.awt.Dimension(800, 700)); // Set a fixed size for the Login panel
        background.add(lg, new java.awt.GridBagConstraints()); // Center the Login panel

        // Ensure components are displayed correctly
        jLayeredPane1.revalidate();
        jLayeredPane1.repaint();

        // Center the JFrame
        setLocationRelativeTo(null);
    }


    


    public static void main(String[] args) {
        // Launch the application
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Template().setVisible(true);
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
